import math

class Calculadora:
    def adicionar(self, a, b):
        return a + b

    def subtrair(self, a, b):
        return a - b

    def multiplicar(self, a, b):
        return a * b

    def dividir(self, a, b):
        if b == 0:
            return "Erro: Divisão por zero."
        return a / b

    def potencia(self, base, expoente):
        return math.pow(base, expoente)

    def raiz_quadrada(self, a):
        if a < 0:
            return "Erro: Raiz quadrada de número negativo."
        return math.sqrt(a)

    def seno(self, angulo):
        return math.sin(math.radians(angulo))

    def cosseno(self, angulo):
        return math.cos(math.radians(angulo))

    def tangente(self, angulo):
        return math.tan(math.radians(angulo))

    def logaritmo(self, valor, base=10):
        if valor <= 0:
            return "Erro: Logaritmo de número não positivo."
        return math.log(valor, base)

    def fatorial(self, n):
        if n < 0:
            return "Erro: Fatorial de número negativo."
        return math.factorial(n)

    def menu(self):
        print("Selecione a operação:")
        print("1. Adição")
        print("2. Subtração")
        print("3. Multiplicação")
        print("4. Divisão")
        print("5. Potência")
        print("6. Raiz Quadrada")
        print("7. Seno")
        print("8. Cosseno")
        print("9. Tangente")
        print("10. Logaritmo")
        print("11. Fatorial")
        print("0. Sair")

        while True:
            escolha = input("Digite a opção (0 a 11): ")

            if escolha == '0':
                print("Saindo da calculadora.")
                break

            if escolha in ['1', '2', '3', '4', '5']:
                a = float(input("Digite o primeiro número: "))
                b = float(input("Digite o segundo número: "))

                if escolha == '1':
                    print("Resultado:", self.adicionar(a, b))
                elif escolha == '2':
                    print("Resultado:", self.subtrair(a, b))
                elif escolha == '3':
                    print("Resultado:", self.multiplicar(a, b))
                elif escolha == '4':
                    print("Resultado:", self.dividir(a, b))
                elif escolha == '5':
                    print("Resultado:", self.potencia(a, b))

            elif escolha == '6':
                a = float(input("Digite o número: "))
                print("Resultado:", self.raiz_quadrada(a))

            elif escolha in ['7', '8', '9']:
                angulo = float(input("Digite o ângulo em graus: "))
                if escolha == '7':
                    print("Resultado:", self.seno(angulo))
                elif escolha == '8':
                    print("Resultado:", self.cosseno(angulo))
                elif escolha == '9':
                    print("Resultado:", self.tangente(angulo))

            elif escolha == '10':
                valor = float(input("Digite o valor: "))
                base = input("Digite a base (pressione Enter para base 10): ")
                base = float(base) if base else 10
                print("Resultado:", self.logaritmo(valor, base))

            elif escolha == '11':
                n = int(input("Digite um número inteiro: "))
                print("Resultado:", self.fatorial(n))

            else:
                print("Opção inválida. Tente novamente.")

if __name__ == "__main__":
    calc = Calculadora()
    calc.menu()
